title: "buenalquiler.com" # the name of your site, e.g. ACME Corp.
tagline: "Alquiler de Departamentos en Lima"
email: "your.email@gmail.com"
description: "Encuentra la mejor oferta de departamentos en alquiler en Lima. Actualmente tenemos disponibles en San Miguel"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
author: name

sass:
 sass_dir: assets/css

plugins:
  
  - jekyll-seo-tag
  - jekyll-sitemap


twitter:
  username: 
  card: summary #keep this to generate a twitter share card

exclude:
  - Gemfile
  - Gemfile.lock