

sass:
 sass_dir: assets/css

plugins:
  
  - jekyll-seo-tag
  - jekyll-sitemap

title: "Jekyll Bootstrap Starter" # the name of your site, e.g. ACME Corp.
tagline: "An awesome tagline"
email: "your.email@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
author: name
baseurl: "/" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com


twitter:
  username: 
  card: summary #keep this to generate a twitter share card

exclude:
  - Gemfile
  - Gemfile.lock