# Site
name: 'buenAlquiler'
description: 'Aprenda conceptos básicos de educación financiera antes de invertir en inmuebles'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: "https://buenalquiler.com"
baseurl: ''
disqus: 'buenalquiler'
email: 'buenalquilerinfo@gmail.com'
google_analytics: 'G-GVKG51G7GK'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
  sal:
    name: buenAlquiler
    site: https://buenalquiler.com/
    avatar: 'assets/images/avatar1.jpg'
    bio: "Blogger en educación financiera"
    email: buenalquilerinfo@gmail.com

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: '/assets/images/avatar1.jpg'
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "pub-9154513114335042"
adsense-data-ad-slot: "1269872539"
